version: '3.7'

# 全コンテナに適用するために定義する
x-global: &global
  restart: always # コンテナが終了しても自動で再起動する
  environment:
    TZ: Asia/Tokyo # タイムゾーンを日本時間にする
  stop_grace_period: 1m # KILLシグナルが送信されるまでの期間を1分に伸ばしてプラグインなどのデータを安全に保存する

# 廃止予定
x-legacy: &legacy
  <<: *global
  working_dir: /legacyapp
  tty: true
  stop_signal: SIGINT

services:
  # プロキシ
  nginx:
    <<: *global
    image: nginx:1-alpine
    ports:
      - 25566:810
    volumes:
      - ./assets/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - azisaba-bungee

  # データベース
  azisaba-mariadb:
    <<: *global
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1 # rootパスワードを自動生成する
    ports:
      - 3306:3306
    volumes:
      - ./save/mariadb:/var/lib/mysql
      - ./assets/initdb.d:/docker-entrypoint-initdb.d
    command: --max-connections=1000 # 最大コネクション数を増やしてLuckPermsの接続エラー対策をする
  azisaba-redis:
    <<: *global
    image: redis:6-alpine

  # マインクラフトサーバー
  azisaba-bungee:
    <<: *global
    build:
      context: bungee
      dockerfile: ../Dockerfile
      args:
        SOFTWARE_URL: https://papermc.io/api/v1/waterfall/1.16/388/download
        SOFTWARE_PORT: 25577
        SOFTWARE_STOP_COMMAND: end
        JAVA_VERSION: 15
    ports:
      - 8192:8192
      - 25565:25577
    depends_on:
      - azisaba-mariadb
  azisaba-lobby:
    <<: *global
    build:
      context: lobby
      dockerfile: ../Dockerfile
      args:
        SOFTWARE_URL: https://papermc.io/api/v1/paper/1.12.2/1618/download
        SOFTWARE_EULA: 1
        JAVA_VERSION: 15
    depends_on:
      - azisaba-mariadb
    volumes:
      - ./save/lobby/world/playerdata:/app/world/playerdata
      - ./save/lobby/lobby:/app/lobby
  azisaba-lgw:
    <<: *legacy
    image: openjdk:8
    volumes:
      - /srv/lgw:/legacyapp
    command: java -jar paper-1.12.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-life:
    <<: *legacy
    image: openjdk:14
    volumes:
      - /srv/life:/legacyapp
    command: java -jar paper-1.15.2.jar
    depends_on:
      - azisaba-mariadb
      - azisaba-redis
  azisaba-sclat:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclat:/legacyapp
    command: java -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv1:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv1:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv2:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv2:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv3:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv3:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv4:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv4:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv5:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv5:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv6:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv6:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv7:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv7:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv8:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv8:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv9:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv9:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclatsv10:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclatsv10:/legacyapp
    command: java -XX:ActiveProcessorCount=4 -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclattest:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclattest:/legacyapp
    command: java -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclattutorial1:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclattutorial1:/legacyapp
    command: java -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclattutorial2:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclattutorial2:/legacyapp
    command: java -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
  azisaba-sclattutorial3:
    <<: *legacy
    image: openjdk:13
    volumes:
      - /srv/sclattutorial3:/legacyapp
    command: java -jar paper-1.13.2.jar
    depends_on:
      - azisaba-mariadb
